name: Deploy
on:
  pull_request:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.AVERLIST_HOST }} >> ~/.ssh/known_hosts
      - name: Install SSH Keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AVERLIST_KEY }}
          known_hosts: ${{ secrets.AVERLIST_KNOWN_HOST }}
      - name: Connect And Pull
        run: ssh ${{ secrets.AVERLIST_USER }}@${{ secrets.AVERLIST_HOST }} "sh /root/deploy-averlist.sh"
      - name: Cleanup
        run: rm -rf ~/.ssh